language: csharp
sudo: false
mono: none
os:
  - linux
  - osx
dotnet: 3.1.300
dist: xenial
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
script:
 - ulimit -n 512; dotnet restore && ls test/**/*.csproj | grep -v 'ActiveMq' | xargs -L1 dotnet test -c Release